[package]
name = "flowent"
version = "0.0.1"
description = "Flowent desktop application"
authors = ["ImFeH2"]
edition = "2021"

[lib]
name = "flowent_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
