[project]
name = "flowent"
version = "0.3.14"
description = "Just say what you need. Flowent gets it done."
authors = [
    { name = "ImFeH2", email = "i@feh2.im" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
flowent = "flowent.__main__:main"

[build-system]
requires = ["uv_build>=0.11.16,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.21.0",
    "pytest>=9.1.1",
    "ruff>=0.16.0",
]
